name: Pulse Android App CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > $HOME/pulse-key.jks

      - name: Set up Keystore environment
        run: |
          echo "KEYSTORE_PATH=$HOME/pulse-key.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Debug Keystore File
        run: ls -lah $HOME

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build Signed Release APK
        run: ./gradlew assembleRelease

      - name: Upload Signed Release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: app/build/outputs/apk/release/app-release.apk